### ISSUE TITLE
use jetpack compose

### ISSUE THREAD

**Issue by beeazy** [beeazy/TappaEvents#2]
The project currently uses xml layouts. I would like to refactor to use compose

**Comment by AnirudhPudari** [comment]
@beeazy Hey, can you assign this to me, i can take a look?

**Comment by beeazy** [comment]
> @beeazy Hey, can you assign this to me, i can take a look?

hey man sorry for rather slow response. I appreciate your offer to help. I already started on the same and have completely phased out xml layouts. I would still love to collaborate on other issues that I will open.
